packages:
  - packages/*
  - apps/*
overrides:
  react: 19.1.0
  react-dom: 19.1.0
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - nestjs-pino
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
