packages:
  - packages/*
  - apps/*
strictPeerDependencies: true
peerDependencyRules:
  allowedVersions:
    # A lot of expo / react-native linting rules and packages are targeting eslint 8, but should work with eslint 9
    eslint: "9"
# We override dependencies here to ensure that the correct version of the dependency is used for each package
catalogs:
  frontend:
    # React
    react: ^19.2.4
    react-dom: ^19.2.4
    "@types/react": ^19.2.10
    "@types/react-dom": ^19.2.3
    # React Router
    react-router: ^7.13.0
    "@react-router/node": ^7.13.0
    "@react-router/serve": ^7.13.0
    "@react-router/dev": ^7.13.0
    react-router-devtools: ^6.2.0
    # Tanstack
    "@tanstack/react-query": ^5.90.20
    # React Hook Form
    react-hook-form: ^7.71.1
    "@hookform/resolvers": ^5.2.2
    # Tailwind CSS
    tailwindcss: ^4.1.18
    tailwindcss-animate: ^1.0.7
    tailwind-merge: ^3.4.0
    "@tailwindcss/vite": ^4.1.18
    "@tailwindcss/typography": ^0.5.19
    react-i18next: ^16.5.4
    i18next: ^25.8.0
  auth:
    # Better Auth
    better-auth: ^1.4.18
    "@better-auth/expo": ^1.4.6
  build:
    # Node, vite, ts
    "@types/node": ^25.1.0
    vite: ^7.3.1
    "vite-tsconfig-paths": ^6.0.5
    typescript: ^5.9.3
  validation:  
    # Zod
    zod: ~4.3.6
    zod-openapi: 5.4.6
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - nestjs-pino
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver