// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { Account } from '../auth/entities/account.entity.js'
import { Comment } from '../example/comments/comments.entity.js'
import { Post, PostVersion } from '../example/posts/posts.entity.js'
import { Session } from '../auth/entities/session.entity.js'
import { Tag } from '../example/tags/tag.entity.js'
import { User } from '../auth/entities/user.entity.js'
import { Verification } from '../auth/entities/verification.entity.js'
import { EntityManager as DriverEntityManager } from '@mikro-orm/postgresql'

export const entities = [
  Account,
  Comment,
  Post,
  PostVersion,
  Session,
  Tag,
  User,
  Verification,
] as const

export type Database = typeof entities

export type EntityManager = DriverEntityManager & { '~entities': Database }
export const EntityManager = DriverEntityManager
