name: Setup Bun
description: Setup Bun runtime

inputs:
  bun-version:
    description: Bun version
    required: false
    default: 1.3.3

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: bun/action-setup@v1
      with:
        version: ${{ inputs.bun-version }}
