// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreateCommentSchema
 *
 * Schema for creating a comment
 */
export const zCreateCommentSchema = z.object({
    content: z.string().min(1).max(1000),
    parentId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/))
});

/**
 * CommentSchema
 *
 * Schema for a comment
 */
export const zCommentSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    content: z.string(),
    authorName: z.union([
        z.string(),
        z.null()
    ]),
    createdAt: z.string(),
    user: z.union([
        z.object({
            id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            name: z.string()
        }),
        z.null()
    ]),
    parentId: z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ]),
    replyIds: z.optional(z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/))),
    replyCount: z.optional(z.number())
});

/**
 * UpdateCommentSchema
 *
 * Schema for updating a comment
 */
export const zUpdateCommentSchema = z.object({
    content: z.string().min(1).max(1000)
});

/**
 * PaginationQuerySchema
 *
 * Schema for pagination query
 */
export const zPaginationQuerySchema = z.object({
    offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
    pageSize: z.optional(z.int().gte(1).lte(100)).default(20)
});

/**
 * SortingQueryStringSchema
 *
 * Schema for sorting items
 */
export const zSortingQueryStringSchema = z.string();

/**
 * FilterQueryStringSchema
 *
 * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
 * Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
 * Available properties: title, tag
 */
export const zFilterQueryStringSchema = z.string();

/**
 * CommentsSchema
 *
 * Schema for a paginated list of comments
 */
export const zCommentsSchema = z.object({
    data: z.array(zCommentSchema),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * PostContentSchema
 *
 * Schema for content items (text, image, video)
 */
export const zPostContentSchema = z.union([
    z.object({
        type: z.enum(['text']),
        data: z.string()
    }),
    z.object({
        type: z.enum(['image']),
        data: z.string()
    }),
    z.object({
        type: z.enum(['video']),
        data: z.string()
    })
]);

/**
 * CreatePostSchema
 *
 * Schema for creating/updating a post
 */
export const zCreatePostSchema = z.object({
    title: z.string().min(1),
    content: z.array(zPostContentSchema),
    coverImage: z.optional(z.url()),
    tags: z.optional(z.array(z.string()))
});

/**
 * PostVersionSchema
 *
 * Schema for a post version
 */
export const zPostVersionSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    title: z.string(),
    createdAt: z.string()
});

/**
 * TagSchema
 *
 * A tag attached to a post
 */
export const zTagSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    slug: z.string()
});

/**
 * UserPostSchema
 *
 * Schema for a user's post
 */
export const zUserPostSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    title: z.string(),
    content: z.array(zPostContentSchema),
    versions: z.array(zPostVersionSchema),
    publishedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.enum(['published', 'draft']),
    commentCount: z.optional(z.number()),
    coverImage: z.optional(z.url()),
    tags: z.array(zTagSchema)
});

/**
 * UpdatePostSchema
 *
 * Schema for updating a post
 */
export const zUpdatePostSchema = z.object({
    title: z.optional(z.string().min(1)),
    content: z.optional(z.array(zPostContentSchema)),
    coverImage: z.optional(z.url()),
    tags: z.optional(z.array(z.string()))
});

/**
 * UserPostsSchema
 *
 * Schema for a list of user's posts
 */
export const zUserPostsSchema = z.object({
    data: z.array(z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        slug: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        title: z.string(),
        versions: z.array(zPostVersionSchema),
        publishedAt: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        type: z.enum(['published', 'draft']),
        commentCount: z.optional(z.number()),
        coverImage: z.optional(z.url()),
        tags: z.array(zTagSchema),
        contentPreview: zPostContentSchema
    })),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * PublicPostSchema
 *
 * A public post
 */
export const zPublicPostSchema = z.object({
    title: z.string(),
    author: z.object({
        name: z.string()
    }),
    content: z.array(zPostContentSchema),
    publishedAt: z.string(),
    slug: z.optional(z.string()),
    commentCount: z.optional(z.number()),
    coverImage: z.optional(z.url()),
    likesCount: z.number(),
    tags: z.array(zTagSchema)
});

/**
 * PublicPostsSchema
 *
 * A list of public posts
 */
export const zPublicPostsSchema = z.object({
    data: z.array(z.object({
        title: z.string(),
        author: z.object({
            name: z.string()
        }),
        publishedAt: z.string(),
        slug: z.optional(z.string()),
        commentCount: z.optional(z.number()),
        coverImage: z.optional(z.url()),
        likesCount: z.number(),
        tags: z.array(zTagSchema),
        contentPreview: zPostContentSchema
    })),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * PublicAuthorPostsSchema
 *
 * A list of posts from a specific author
 */
export const zPublicAuthorPostsSchema = z.object({
    data: z.array(z.object({
        title: z.string(),
        author: z.object({
            name: z.string()
        }),
        publishedAt: z.string(),
        slug: z.optional(z.string()),
        commentCount: z.optional(z.number()),
        coverImage: z.optional(z.url()),
        likesCount: z.number(),
        tags: z.array(zTagSchema),
        contentPreview: zPostContentSchema
    })),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * AiGenerateOptions
 *
 * Options for an AI generation
 */
export const zAiGenerateOptions = z.object({
    temperature: z.optional(z.number().gte(0).lte(2)),
    maxTokens: z.optional(z.number().gt(0)),
    topP: z.optional(z.number().gte(0).lte(1)),
    frequencyPenalty: z.optional(z.number().gte(-2).lte(2)),
    presencePenalty: z.optional(z.number().gte(-2).lte(2)),
    maxSteps: z.optional(z.number().gt(0)),
    stopWhen: z.optional(z.number().gt(0)),
    telemetry: z.optional(z.object({
        traceMode: z.optional(z.enum(['inherit', 'split'])),
        traceId: z.optional(z.string()),
        traceName: z.optional(z.string()),
        spanName: z.optional(z.string()),
        sessionId: z.optional(z.string()),
        metadata: z.optional(z.record(z.string(), z.unknown())),
        langfuseOriginalPrompt: z.optional(z.string())
    })),
    metadata: z.optional(z.record(z.string(), z.unknown()))
});

/**
 * GenerateTextRequest
 *
 * Request for simple text generation with a single prompt
 */
export const zGenerateTextRequest = z.object({
    prompt: z.string().min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * TokenUsage
 *
 * Token usage information for an AI generation
 */
export const zTokenUsage = z.object({
    promptTokens: z.number(),
    completionTokens: z.number(),
    totalTokens: z.number()
});

/**
 * ToolCall
 *
 * A tool call made by the AI
 */
export const zToolCall = z.object({
    toolCallId: z.string(),
    toolName: z.string(),
    args: z.record(z.string(), z.unknown())
});

/**
 * ToolResult
 *
 * The result of a tool call
 */
export const zToolResult = z.object({
    toolCallId: z.string(),
    toolName: z.string(),
    result: z.unknown()
});

/**
 * GenerateTextResponse
 *
 * Response from text generation
 */
export const zGenerateTextResponse = z.object({
    usage: z.optional(zTokenUsage),
    finishReason: z.optional(z.string()),
    toolCalls: z.optional(z.array(zToolCall)),
    toolResults: z.optional(z.array(zToolResult)),
    result: z.string()
});

/**
 * GenerateObjectRequest
 *
 * Request for structured object generation with a predefined schema type
 */
export const zGenerateObjectRequest = z.object({
    prompt: z.string().min(1),
    schemaType: z.enum([
        'userProfile',
        'task',
        'product',
        'recipe'
    ]),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * GenerateObjectResponse
 *
 * Response from structured object generation
 */
export const zGenerateObjectResponse = z.object({
    usage: z.optional(zTokenUsage),
    finishReason: z.optional(z.string()),
    toolCalls: z.optional(z.array(zToolCall)),
    toolResults: z.optional(z.array(zToolResult)),
    result: z.unknown()
});

/**
 * ChatSchemaType
 *
 * Predefined schema types for testing structured output
 */
export const zChatSchemaType = z.enum([
    'userProfile',
    'task',
    'product',
    'recipe',
    'none'
]);

/**
 * ChatMessageWithSchemaType
 *
 * A message with optional schemaType metadata for identifying structured output
 */
export const zChatMessageWithSchemaType = z.object({
    role: z.enum([
        'user',
        'assistant',
        'system',
        'tool'
    ]),
    content: z.string(),
    metadata: z.optional(z.object({
        isConsideredSystemMessage: z.optional(z.boolean()),
        usage: z.optional(zTokenUsage),
        finishReason: z.optional(z.string()),
        timestamp: z.optional(z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/)),
        toolCalls: z.optional(z.array(zToolCall)),
        reasonning: z.optional(z.string()),
        schemaType: z.optional(zChatSchemaType)
    }))
});

/**
 * ChatRequest
 *
 * Request for multi-turn AI conversation with message history. schemaType can be used to request structured output.
 */
export const zChatRequest = z.object({
    messages: z.array(zChatMessageWithSchemaType).min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions),
    schemaType: z.optional(zChatSchemaType)
});

/**
 * ChatResponse
 *
 * Response from AI chat conversation
 */
export const zChatResponse = z.object({
    usage: z.optional(zTokenUsage),
    finishReason: z.optional(z.string()),
    toolCalls: z.optional(z.array(zToolCall)),
    toolResults: z.optional(z.array(zToolResult)),
    result: z.string(),
    messages: z.array(zChatMessageWithSchemaType)
});

/**
 * StreamTextRequest
 *
 * Request for streaming text generation with a single prompt
 */
export const zStreamTextRequest = z.object({
    prompt: z.string().min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * StreamObjectRequest
 *
 * Request for streaming structured object generation
 */
export const zStreamObjectRequest = z.object({
    prompt: z.string().min(1),
    schemaType: z.enum([
        'userProfile',
        'task',
        'product',
        'recipe'
    ]),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * StreamChatRequest
 *
 * Request for streaming multi-turn AI conversation
 */
export const zStreamChatRequest = z.object({
    messages: z.array(zChatMessageWithSchemaType).min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * UseCase1SingleGenerationRequest
 *
 * Single generation; trace is finalized with name/output so Langfuse shows them
 */
export const zUseCase1SingleGenerationRequest = z.object({
    prompt: z.string().min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ])),
    options: z.optional(zAiGenerateOptions)
});

/**
 * UseCase2GroupedCallsRequest
 *
 * Multiple LLM calls in one request; one trace in Langfuse, finalized at end
 */
export const zUseCase2GroupedCallsRequest = z.object({
    prompts: z.array(z.string().min(1)).min(1).max(5),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ]))
});

/**
 * UseCase2GroupedCallsResponse
 *
 * Combined results from grouped LLM calls
 */
export const zUseCase2GroupedCallsResponse = z.object({
    traceName: z.string(),
    results: z.array(z.string()),
    usage: z.optional(zTokenUsage)
});

/**
 * UseCase3LogicalUnitsRequest
 *
 * Multiple workflows; each workflow gets its own Langfuse trace (split per unit)
 */
export const zUseCase3LogicalUnitsRequest = z.object({
    workflowPrompts: z.array(z.string().min(1)).min(1).max(5),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ]))
});

/**
 * UseCase3LogicalUnitsResponse
 *
 * One result per workflow (each in its own trace)
 */
export const zUseCase3LogicalUnitsResponse = z.object({
    workflows: z.array(z.object({
        index: z.number(),
        result: z.string(),
        usage: z.optional(zTokenUsage)
    }))
});

/**
 * UseCase4ChatSessionRequest
 *
 * Simple generateText with sessionId for grouping traces across requests
 */
export const zUseCase4ChatSessionRequest = z.object({
    prompt: z.string().min(1),
    sessionId: z.string().min(1),
    model: z.optional(z.enum([
        'OPENAI_GPT_5_NANO',
        'GOOGLE_GEMINI_3_FLASH',
        'CLAUDE_HAIKU_3_5',
        'CLAUDE_OPUS_4_5',
        'MISTRAL_SMALL'
    ]))
});

/**
 * AiCoreMessage
 *
 * A message in the conversation history following Vercel AI SDK patterns
 */
export const zAiCoreMessage = z.object({
    role: z.enum([
        'user',
        'assistant',
        'system',
        'tool'
    ]),
    content: z.string(),
    metadata: z.optional(z.object({
        isConsideredSystemMessage: z.optional(z.boolean()),
        usage: z.optional(zTokenUsage),
        finishReason: z.optional(z.string()),
        timestamp: z.optional(z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/)),
        toolCalls: z.optional(z.array(zToolCall)),
        reasonning: z.optional(z.string())
    }))
});

/**
 * AiStreamTextChunkEvent
 *
 * A text chunk event during streaming
 */
export const zAiStreamTextChunkEvent = z.object({
    type: z.literal('chunk'),
    text: z.string()
});

/**
 * AiStreamToolCallEvent
 *
 * Event when a tool is being called during streaming
 */
export const zAiStreamToolCallEvent = z.object({
    type: z.literal('tool-call'),
    toolCallId: z.string(),
    toolName: z.string(),
    args: z.record(z.string(), z.unknown())
});

/**
 * AiStreamToolResultEvent
 *
 * Event when a tool returns a result during streaming
 */
export const zAiStreamToolResultEvent = z.object({
    type: z.literal('tool-result'),
    toolCallId: z.string(),
    toolName: z.string(),
    result: z.unknown()
});

/**
 * AiStreamUsage
 *
 * Token usage information for the stream
 */
export const zAiStreamUsage = z.object({
    promptTokens: z.number(),
    completionTokens: z.number(),
    totalTokens: z.number()
});

/**
 * AiStreamDoneEvent
 *
 * Final event when streaming is complete
 */
export const zAiStreamDoneEvent = z.object({
    type: z.literal('done'),
    fullText: z.string(),
    usage: z.optional(zAiStreamUsage),
    finishReason: z.optional(z.string())
});

/**
 * AiStreamErrorEvent
 *
 * Error event during streaming
 */
export const zAiStreamErrorEvent = z.object({
    type: z.literal('error'),
    message: z.string()
});

/**
 * AiStreamEvent
 *
 * SSE event for AI text streaming with tool support
 */
export const zAiStreamEvent = z.union([
    zAiStreamTextChunkEvent,
    zAiStreamToolCallEvent,
    zAiStreamToolResultEvent,
    zAiStreamDoneEvent,
    zAiStreamErrorEvent
]);

/**
 * Task
 *
 * A task
 */
export const zTask = z.object({
    title: z.string(),
    description: z.string(),
    priority: z.enum([
        'low',
        'medium',
        'high'
    ]),
    dueDate: z.optional(z.string()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Product
 *
 * A product
 */
export const zProduct = z.object({
    name: z.string(),
    price: z.number(),
    description: z.string(),
    category: z.string(),
    inStock: z.boolean(),
    features: z.optional(z.array(z.string()))
});

/**
 * Recipe
 *
 * A recipe
 */
export const zRecipe = z.object({
    name: z.string(),
    description: z.string(),
    prepTime: z.string(),
    cookTime: z.string(),
    servings: z.number(),
    difficulty: z.enum([
        'easy',
        'medium',
        'hard'
    ]),
    ingredients: z.array(z.object({
        name: z.string(),
        quantity: z.string()
    })),
    instructions: z.array(z.string()),
    tips: z.optional(z.array(z.string()))
});

/**
 * UserProfile
 *
 * A user profile
 */
export const zUserProfile = z.object({
    name: z.string(),
    age: z.number(),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    bio: z.optional(z.string()),
    skills: z.optional(z.array(z.string()))
});

export const zCommentsControllerGetCommentsSortItem = z.object({
    property: z.enum(['createdAt', 'authorName']),
    direction: z.enum(['asc', 'desc'])
});

export const zCommentsControllerGetCommentsSortArray = z.array(zCommentsControllerGetCommentsSortItem);

export const zCommentsControllerGetCommentsFilterItem = z.object({
    property: z.enum(['content']),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zCommentsControllerGetCommentsFilterArray = z.array(zCommentsControllerGetCommentsFilterItem);

export const zCommentsControllerGetCommentRepliesSortItem = z.object({
    property: z.enum(['createdAt', 'authorName']),
    direction: z.enum(['asc', 'desc'])
});

export const zCommentsControllerGetCommentRepliesSortArray = z.array(zCommentsControllerGetCommentRepliesSortItem);

export const zPostControllerGetUserPostsSortItem = z.object({
    property: z.enum(['title', 'createdAt']),
    direction: z.enum(['asc', 'desc'])
});

export const zPostControllerGetUserPostsSortArray = z.array(zPostControllerGetUserPostsSortItem);

export const zPostControllerGetUserPostsFilterItem = z.object({
    property: z.enum(['title', 'tag']),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zPostControllerGetUserPostsFilterArray = z.array(zPostControllerGetUserPostsFilterItem);

export const zPublicPostControllerGetPostsSortItem = z.object({
    property: z.enum(['title', 'createdAt']),
    direction: z.enum(['asc', 'desc'])
});

export const zPublicPostControllerGetPostsSortArray = z.array(zPublicPostControllerGetPostsSortItem);

export const zPublicPostControllerGetPostsFilterItem = z.object({
    property: z.enum(['title', 'tag']),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zPublicPostControllerGetPostsFilterArray = z.array(zPublicPostControllerGetPostsFilterItem);

export const zPublicAuthorControllerGetAuthorPostsSortItem = z.object({
    property: z.enum(['title', 'createdAt']),
    direction: z.enum(['asc', 'desc'])
});

export const zPublicAuthorControllerGetAuthorPostsSortArray = z.array(zPublicAuthorControllerGetAuthorPostsSortItem);

export const zAppControllerGetHelloData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCommentsControllerGetCommentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        postSlug: z.string()
    }),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
        pageSize: z.optional(z.int().gte(1).lte(100)).default(20),
        sort: z.optional(zCommentsControllerGetCommentsSortArray),
        filter: z.optional(zCommentsControllerGetCommentsFilterArray)
    }))
});

export const zCommentsControllerGetCommentsResponse = zCommentsSchema;

export const zCommentsControllerCreateCommentData = z.object({
    body: z.object({
        content: z.string().min(1).max(1000),
        parentId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/))
    }),
    path: z.object({
        postSlug: z.string()
    }),
    query: z.optional(z.never())
});

export const zCommentsControllerCreateCommentResponse = zCommentSchema;

export const zCommentsControllerDeleteCommentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        commentId: z.string(),
        postSlug: z.string()
    }),
    query: z.optional(z.never())
});

export const zCommentsControllerUpdateCommentData = z.object({
    body: z.object({
        content: z.string().min(1).max(1000)
    }),
    path: z.object({
        postSlug: z.string(),
        commentId: z.string()
    }),
    query: z.optional(z.never())
});

export const zCommentsControllerUpdateCommentResponse = zCommentSchema;

export const zCommentsControllerGetCommentCountData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        postSlug: z.string()
    }),
    query: z.optional(z.never())
});

export const zCommentsControllerGetCommentRepliesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        commentId: z.string(),
        postSlug: z.string()
    }),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
        pageSize: z.optional(z.int().gte(1).lte(100)).default(20),
        sort: z.optional(zCommentsControllerGetCommentRepliesSortArray)
    }))
});

export const zCommentsControllerGetCommentRepliesResponse = zCommentsSchema;

export const zPostControllerGetUserPostsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
        pageSize: z.optional(z.int().gte(1).lte(100)).default(20),
        sort: z.optional(zPostControllerGetUserPostsSortArray),
        filter: z.optional(zPostControllerGetUserPostsFilterArray)
    }))
});

export const zPostControllerGetUserPostsResponse = zUserPostsSchema;

export const zPostControllerCreatePostData = z.object({
    body: z.object({
        title: z.string().min(1),
        content: z.array(zPostContentSchema),
        coverImage: z.optional(z.url()),
        tags: z.optional(z.array(z.string()))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostControllerCreatePostResponse = zUserPostSchema;

export const zPostControllerGetUserPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPostControllerGetUserPostResponse = zUserPostSchema;

export const zPostControllerUpdatePostData = z.object({
    body: z.object({
        title: z.optional(z.string().min(1)),
        content: z.optional(z.array(zPostContentSchema)),
        coverImage: z.optional(z.url()),
        tags: z.optional(z.array(z.string()))
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPostControllerUpdatePostResponse = zUserPostSchema;

export const zPostControllerPublishPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPostControllerPublishPostResponse = zUserPostSchema;

export const zPostControllerUnpublishPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPostControllerUnpublishPostResponse = zUserPostSchema;

export const zPublicPostControllerGetRandomPostData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPublicPostControllerGetRandomPostResponse = zPublicPostSchema;

export const zPublicPostControllerGetPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        slug: z.string()
    }),
    query: z.optional(z.never())
});

export const zPublicPostControllerGetPostResponse = zPublicPostSchema;

export const zPublicPostControllerGetPostsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
        pageSize: z.optional(z.int().gte(1).lte(100)).default(20),
        sort: z.optional(zPublicPostControllerGetPostsSortArray),
        filter: z.optional(zPublicPostControllerGetPostsFilterArray)
    }))
});

export const zPublicPostControllerGetPostsResponse = zPublicPostsSchema;

export const zPublicPostControllerLikePostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        slug: z.string()
    }),
    query: z.optional(z.never())
});

export const zPublicPostControllerLikePostResponse = zPublicPostSchema;

export const zPublicAuthorControllerGetAuthorPostsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        slug: z.string()
    }),
    query: z.optional(z.object({
        offset: z.optional(z.int().gte(0).lte(9007199254740991)).default(0),
        pageSize: z.optional(z.int().gte(1).lte(100)).default(20),
        sort: z.optional(zPublicAuthorControllerGetAuthorPostsSortArray)
    }))
});

export const zPublicAuthorControllerGetAuthorPostsResponse = zPublicAuthorPostsSchema;

export const zAiExampleControllerGenerateTextData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleControllerGenerateTextResponse = zGenerateTextResponse;

export const zAiExampleControllerGenerateObjectData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        schemaType: z.enum([
            'userProfile',
            'task',
            'product',
            'recipe'
        ]),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleControllerGenerateObjectResponse = zGenerateObjectResponse;

export const zAiExampleControllerChatData = z.object({
    body: z.object({
        messages: z.array(zChatMessageWithSchemaType).min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions),
        schemaType: z.optional(zChatSchemaType)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleControllerChatResponse = zChatResponse;

export const zAiExampleControllerStreamTextData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleControllerStreamObjectData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        schemaType: z.enum([
            'userProfile',
            'task',
            'product',
            'recipe'
        ]),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleControllerStreamChatData = z.object({
    body: z.object({
        messages: z.array(zChatMessageWithSchemaType).min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase1SingleGenerationData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ])),
        options: z.optional(zAiGenerateOptions)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase1SingleGenerationResponse = zGenerateTextResponse;

export const zAiExampleUseCasesControllerUseCase2GroupedCallsData = z.object({
    body: z.object({
        prompts: z.array(z.string().min(1)).min(1).max(5),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase2GroupedCallsResponse = zUseCase2GroupedCallsResponse;

export const zAiExampleUseCasesControllerUseCase3LogicalUnitsData = z.object({
    body: z.object({
        workflowPrompts: z.array(z.string().min(1)).min(1).max(5),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase3LogicalUnitsResponse = zUseCase3LogicalUnitsResponse;

export const zAiExampleUseCasesControllerUseCase4ChatSessionData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        sessionId: z.string().min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase4ChatSessionResponse = zGenerateTextResponse;

export const zAiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedData = z.object({
    body: z.object({
        prompt: z.string().min(1),
        sessionId: z.string().min(1),
        model: z.optional(z.enum([
            'OPENAI_GPT_5_NANO',
            'GOOGLE_GEMINI_3_FLASH',
            'CLAUDE_HAIKU_3_5',
            'CLAUDE_OPUS_4_5',
            'MISTRAL_SMALL'
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponse = zGenerateTextResponse;
